# Generated by Django 5.1.4 on 2026-09-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0050_add_largo_to_pedidoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=True)),
                ('iniciada', models.DateTimeField(auto_now_add=True)),
                ('cerrada', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VariantePreparada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('confirmada', models.DateTimeField(blank=True, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preparacion', to='boutique.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('emitida', models.DateTimeField(auto_now_add=True)),
                ('contada', models.DateTimeField(blank=True, null=True)),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piezas', to='preparacion.jornadaconteo')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piezas', to='preparacion.variantepreparada')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jornadaconteo',
            constraint=models.UniqueConstraint(condition=models.Q(('abierta', True)), fields=('abierta',), name='una_jornada_inicial_abierta'),
        ),
    ]
