# Generated by Django 5.1.4 on 2026-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezaetiqueta',
            name='vendida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
