# Generated by Django 5.1.4 on 2026-09-25 21:35

from django.db import migrations, models


def copiar_cantidad_existente(apps, schema_editor):
    Variante = apps.get_model('preparacion', 'VariantePreparada')
    for variante in Variante.objects.select_related('producto').iterator():
        if variante.producto.cantidad_actual:
            Variante.objects.filter(pk=variante.pk).update(
                cantidad_estimada=variante.producto.cantidad_actual)


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0002_piezaetiqueta_vendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantepreparada',
            name='cantidad_estimada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(copiar_cantidad_existente, migrations.RunPython.noop),
    ]
