# Generated by Django 5.1.4 on 2026-10-02 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0050_add_largo_to_pedidoitem'),
        ('preparacion', '0003_variantepreparada_cantidad_estimada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='piezaetiqueta',
            name='encargado',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='piezaetiqueta',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ARREGLO', 'En arreglo'), ('MUESTRA', 'Muestra para réplica'), ('REVISION', 'En revisión'), ('APARTADA', 'Apartada'), ('VENDIDA', 'Vendida')], default='DISPONIBLE', max_length=30),
        ),
        migrations.AddField(
            model_name='piezaetiqueta',
            name='regreso_previsto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piezaetiqueta',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piezaetiqueta',
            name='ubicacion',
            field=models.CharField(choices=[('BOUTIQUE', 'Boutique'), ('BODEGA', 'Bodega'), ('OTRO_LOCAL', 'Otro local'), ('TALLER', 'Taller / costura')], default='BOUTIQUE', max_length=30),
        ),
        migrations.AddField(
            model_name='piezaetiqueta',
            name='ultima_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boutique.venta'),
        ),
        migrations.CreateModel(
            name='OperacionPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.UUIDField(unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('huella', models.CharField(max_length=64)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=30)),
                ('origen', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('encargado', models.CharField(blank=True, max_length=150)),
                ('regreso_previsto', models.DateField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=500)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='preparacion.piezaetiqueta')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boutique.venta')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='preparacion.operacionprendas')),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
            },
        ),
    ]
