# Generated by Django 5.1.4 on 2026-10-03 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0051_modelo_costo_referencia_modelo_precio_sugerido_and_more'),
        ('preparacion', '0006_codigofabricante_entradafabricante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionFabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.UUIDField(unique=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='boutique.producto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='boutique.producto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
