# Generated by Django 6.0.1 on 2026-01-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0002_cliente_pedido_venta_itemventa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_visita", models.DateField()),
                ("fecha_entrega", models.DateField()),
                ("evento", models.CharField(max_length=100)),
                ("notas", models.TextField(blank=True)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("NEGOCIACION", "En Negociación"),
                            ("CONFIRMADO", "Confirmado"),
                            ("PRODUCCION", "En Producción"),
                            ("LISTO", "Listo"),
                            ("ENTREGADO", "Entregado"),
                        ],
                        default="NEGOCIACION",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("TIENDA", "En Tienda"),
                    ("APARTADO", "Apartado"),
                    ("PEDIDO", "Sobre Pedido"),
                ],
                default="TIENDA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrs/"),
        ),
        migrations.AddField(
            model_name="producto",
            name="rasgo1",
            field=models.CharField(
                blank=True, help_text="Ej: Manga Larga, Escote V", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="rasgo2",
            field=models.CharField(
                blank=True, help_text="Ej: Seda, Estilo Sirena", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="IntegranteGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("tela", models.CharField(blank=True, max_length=50)),
                ("talla_medida", models.CharField(blank=True, max_length=50)),
                (
                    "anticipo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boutique.cliente",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="boutique.grupo",
                    ),
                ),
                (
                    "modelo_elegido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Tarjeta"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="boutique.venta",
                    ),
                ),
            ],
        ),
    ]
