# Generated by Django 6.0.1 on 2026-01-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0003_grupo_producto_estado_producto_qr_code_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="producto",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="producto",
            name="modelo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.modelo",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tela",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.tela",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="producto",
            unique_together={
                ("categoria", "modelo", "tela", "color", "talla", "rasgo1", "rasgo2")
            },
        ),
    ]
