# Generated by Django 6.0.1 on 2026-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boutique",
            "0004_alter_producto_unique_together_alter_producto_modelo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="barcode_image",
            field=models.ImageField(blank=True, null=True, upload_to="barcodes/"),
        ),
    ]
