# Generated by Django 6.0.1 on 2026-01-18 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0005_producto_barcode_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorteCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "monto_apertura",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "efectivo_esperado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tarjeta_esperada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "efectivo_real",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tarjeta_real",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "diferencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("cerrado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
