# Generated by Django 5.1.4 on 2026-01-25 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0007_rename_usuario_cortecaja_abierto_por_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("abrir_caja", "Puede abrir caja"),
                            ("vender", "Puede realizar ventas"),
                            ("cobrar", "Puede cobrar"),
                            ("editar_inventario", "Puede editar inventario"),
                            ("ver_reportes", "Puede ver reportes"),
                            ("gestionar_usuarios", "Puede gestionar usuarios"),
                            ("ver_todo", "Acceso total"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tienda",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("direccion", models.TextField(blank=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="auditoria",
            options={"ordering": ["-timestamp"], "verbose_name_plural": "Auditorías"},
        ),
        migrations.AddField(
            model_name="auditoria",
            name="entidad_id",
            field=models.IntegerField(
                blank=True, help_text="ID del objeto afectado", null=True
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="entidad_tipo",
            field=models.CharField(
                blank=True, help_text="Modelo afectado", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("LOGIN_PERFIL", "Selección de perfil"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("APERTURA_CAJA", "Apertura de caja"),
                    ("CIERRE_CAJA", "Cierre de caja"),
                    ("VENTA", "Venta registrada"),
                    ("PAGO", "Pago registrado"),
                    ("MOVIMIENTO_INV", "Movimiento de inventario"),
                    ("EDICION_PRODUCTO", "Edición de producto"),
                    ("ELIMINACION_PRODUCTO", "Eliminación de producto"),
                    ("CREACION_USUARIO", "Creación de usuario"),
                    ("EDICION_USUARIO", "Edición de usuario"),
                    ("CAMBIO_ROL", "Cambio de rol"),
                    ("EXPORTACION", "Exportación de datos"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auditorias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cortecaja",
            name="abierto_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cajas_abiertas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cortecaja",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="integrantegrupo",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="modelo",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tela",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("AJUSTE", "Ajuste"),
                            ("VENTA", "Venta"),
                            ("DEVOLUCION", "Devolución"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra a proveedor"),
                            ("VENTA", "Venta a cliente"),
                            ("MERMA", "Merma/Pérdida"),
                            ("AJUSTE_INVENTARIO", "Ajuste de inventario"),
                            ("DEVOLUCION_PROVEEDOR", "Devolución a proveedor"),
                            ("DEVOLUCION_CLIENTE", "Devolución de cliente"),
                            ("TRANSFERENCIA", "Transferencia entre tiendas"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("stock_resultante", models.IntegerField()),
                (
                    "perfil_activo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="boutique.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.venta",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boutique.tienda",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="auditoria",
            name="tienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.tienda",
            ),
        ),
        migrations.AddField(
            model_name="cortecaja",
            name="tienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="boutique.tienda",
            ),
        ),
    ]
