# Generated by Django 5.1.4 on 2026-01-25 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0008_permiso_tienda_alter_auditoria_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="color",
            options={"ordering": ["familia", "orden", "nombre"]},
        ),
        migrations.AlterModelOptions(
            name="pedido",
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.AlterUniqueTogether(
            name="tela",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="fecha_pedido",
        ),
        migrations.AddField(
            model_name="color",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="color",
            name="es_predefinido",
            field=models.BooleanField(
                default=False, help_text="Colores del catálogo base"
            ),
        ),
        migrations.AddField(
            model_name="color",
            name="familia",
            field=models.CharField(
                blank=True, help_text="Ej: Rosa, Azul, Verde", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="color",
            name="orden",
            field=models.IntegerField(default=0, help_text="Orden de aparición"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.color",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="es_vestido_novia",
            field=models.BooleanField(
                default=False, help_text="Es el vestido de la novia"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("SIN_PAGO", "Sin pago"),
                    ("APARTADO", "Apartado"),
                    ("PARCIAL", "Pago parcial"),
                    ("LIQUIDADO", "Liquidado"),
                ],
                default="SIN_PAGO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_entrega_estimada",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_entrega_real",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="imagen_referencia",
            field=models.ImageField(blank=True, null=True, upload_to="pedidos/"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="modelo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.modelo",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="notas_ajustes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="numero_ticket",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="talla",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tela",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.tela",
            ),
        ),
        migrations.AddField(
            model_name="tela",
            name="activa",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tela",
            name="descripcion",
            field=models.TextField(blank=True, help_text="Características de la tela"),
        ),
        migrations.AddField(
            model_name="tela",
            name="es_predefinida",
            field=models.BooleanField(
                default=False, help_text="Telas del catálogo base"
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="codigo_hex",
            field=models.CharField(
                default="#CCCCCC", help_text="Ej: #FF5733", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("NUEVO", "Nuevo"),
                    ("PENDIENTE_TELA", "Falta comprar tela"),
                    ("TELA_COMPRADA", "Tela comprada"),
                    ("EN_CONFECCION", "En confección"),
                    ("LISTO", "Listo en tienda"),
                    ("ENTREGADO", "Entregado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="NUEVO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                help_text="Si ya existe en inventario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.producto",
            ),
        ),
        migrations.AlterField(
            model_name="tela",
            name="codigo_proveedor",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="tela",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boutique.proveedor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tela",
            unique_together={("nombre", "proveedor")},
        ),
        migrations.CreateModel(
            name="Dama",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("talla", models.CharField(blank=True, max_length=10)),
                (
                    "notas_ajustes",
                    models.TextField(
                        blank=True, help_text="Notas de ajustes específicos"
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.color",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.modelo",
                    ),
                ),
                (
                    "tela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.tela",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pedido",
            name="dama",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="boutique.dama",
            ),
        ),
        migrations.CreateModel(
            name="NotaPedido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_seguimiento",
                        to="boutique.pedido",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Novia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("fecha_boda", models.DateField()),
                (
                    "fecha_prueba",
                    models.DateField(
                        blank=True, help_text="Día de prueba/ajustes", null=True
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateField(blank=True, help_text="Día de entrega", null=True),
                ),
                (
                    "fecha_limite",
                    models.DateField(
                        blank=True, help_text="Fecha límite (antes de boda)", null=True
                    ),
                ),
                ("cantidad_damas", models.PositiveIntegerField(default=0)),
                ("notas", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "color_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novias_color",
                        to="boutique.color",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modelo_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novias_modelo",
                        to="boutique.modelo",
                    ),
                ),
                (
                    "tela_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novias_tela",
                        to="boutique.tela",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_boda"],
            },
        ),
        migrations.AddField(
            model_name="dama",
            name="novia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="damas",
                to="boutique.novia",
            ),
        ),
        migrations.CreateModel(
            name="CitaAgenda",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRUEBA", "Prueba de vestido"),
                            ("AJUSTE", "Ajustes"),
                            ("ENTREGA", "Entrega"),
                            ("RECOGIDA", "Recogida"),
                            ("CONSULTA", "Consulta nueva novia"),
                            ("OTRO", "Otro"),
                        ],
                        default="CONSULTA",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("nombre_cliente", models.CharField(blank=True, max_length=200)),
                ("telefono_cliente", models.CharField(blank=True, max_length=20)),
                ("cantidad_damas_esperadas", models.PositiveIntegerField(default=0)),
                ("notas", models.TextField(blank=True)),
                ("completada", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citas",
                        to="boutique.pedido",
                    ),
                ),
                (
                    "novia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="boutique.novia",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "hora_inicio"],
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="novia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="boutique.novia",
            ),
        ),
        migrations.CreateModel(
            name="PagoPedido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Tarjeta"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        default="EFECTIVO",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("notas", models.CharField(blank=True, max_length=200)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_pedido",
                        to="boutique.pedido",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
