# Generated by Django 5.1.4 on 2026-01-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0008_permiso_tienda_alter_auditoria_options_and_more"),
    ]

    operations = []
