# Generated by Django 5.1.4 on 2026-01-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0009_alter_color_options_alter_pedido_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="novia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="boutique.novia",
            ),
        ),
    ]
