# Generated by Django 5.1.4 on 2026-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0010_alter_pedido_fecha_actualizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dama",
            name="color_especial",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dama",
            name="modelo_especial",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dama",
            name="tela_especial",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="novia",
            name="color_especial",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="novia",
            name="modelo_especial",
            field=models.CharField(
                blank=True, help_text="Para modelos no en catálogo", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="talla_especial",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="novia",
            name="tela_especial",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
