# Generated by Django 5.1.4 on 2026-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0011_dama_color_especial_dama_modelo_especial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock_teorico",
            field=models.IntegerField(default=0),
        ),
    ]
