# Generated by Django 5.1.4 on 2026-01-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0012_producto_stock_teorico"),
    ]

    operations = [
        migrations.AddField(
            model_name="dama",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="novia",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="pendiente_regularizacion",
            field=models.BooleanField(default=False),
        ),
    ]
