# Generated by Django 5.1.4 on 2026-02-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0013_dama_activo_novia_activo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelo",
            options={
                "verbose_name": "Modelo de Producto",
                "verbose_name_plural": "Modelos de Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={
                "verbose_name": "Variante (SKU)",
                "verbose_name_plural": "Variantes (SKU)",
            },
        ),
    ]
