# Generated by Django 5.1.4 on 2026-02-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0014_alter_modelo_options_alter_producto_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="notas",
            field=models.TextField(
                blank=True, help_text="Notas o IDs de sincronización offline"
            ),
        ),
    ]
