# Generated by Django 5.1.4 on 2026-02-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0015_venta_notas"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="anticipo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="venta",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas_asociadas",
                to="boutique.pedido",
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("NOVIA", "Novia"), ("DAMA", "Dama")], max_length=10
                    ),
                ),
                ("folio", models.CharField(blank=True, max_length=20, unique=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("cliente_nombre", models.CharField(blank=True, max_length=200)),
                (
                    "novia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="boutique.novia",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.tienda",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pedido",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="boutique.ticket",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="boutique.ticket",
            ),
        ),
    ]
