# Generated by Django 5.1.4 on 2026-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0016_pedido_anticipo_venta_pedido_ticket_pedido_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="offline_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="offline_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="notas",
            field=models.TextField(blank=True),
        ),
    ]
