# Generated by Django 5.1.4 on 2026-02-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0017_pedido_offline_id_venta_offline_id_alter_venta_notas"),
    ]

    operations = [
        migrations.AddField(
            model_name="dama",
            name="m_altura_busto",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Altura Busto"
            ),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_ancho_espalda",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Ancho Espalda"
            ),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_busto",
            field=models.CharField(blank=True, max_length=50, verbose_name="Busto"),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_cadera",
            field=models.CharField(blank=True, max_length=50, verbose_name="Cadera"),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_cintura",
            field=models.CharField(blank=True, max_length=50, verbose_name="Cintura"),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_largo_total",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Largo Total"
            ),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_notas_medidas",
            field=models.TextField(blank=True, verbose_name="Notas de Medidas"),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_separacion_busto",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Separación Busto"
            ),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_talle_delantero",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Talle Delantero"
            ),
        ),
        migrations.AddField(
            model_name="dama",
            name="m_talle_trasero",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Talle Trasero"
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_altura_busto",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Altura Busto"
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_ancho_espalda",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Ancho Espalda"
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_busto",
            field=models.CharField(blank=True, max_length=50, verbose_name="Busto"),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_cadera",
            field=models.CharField(blank=True, max_length=50, verbose_name="Cadera"),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_cintura",
            field=models.CharField(blank=True, max_length=50, verbose_name="Cintura"),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_largo_total",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Largo Total"
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_notas_medidas",
            field=models.TextField(blank=True, verbose_name="Notas de Medidas"),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_separacion_busto",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Separación Busto"
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_talle_delantero",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Talle Delantero"
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="m_talle_trasero",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Talle Trasero"
            ),
        ),
    ]
