# Generated by Django 5.1.4 on 2026-02-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0018_dama_m_altura_busto_dama_m_ancho_espalda_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionTienda",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(default="Adelé Boutique", max_length=200),
                ),
                ("razon_social", models.CharField(blank=True, max_length=200)),
                (
                    "rfc",
                    models.CharField(blank=True, max_length=20, verbose_name="RFC"),
                ),
                ("direccion", models.TextField(blank=True)),
                (
                    "telefono_whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono/WhatsApp"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "politica_cambios",
                    models.TextField(
                        blank=True, verbose_name="Políticas de Cambios/Devoluciones"
                    ),
                ),
                (
                    "politica_apartados",
                    models.TextField(blank=True, verbose_name="Políticas de Apartados"),
                ),
                (
                    "prefijo_sucursal",
                    models.CharField(default="GDL", help_text="Ej: GDL", max_length=10),
                ),
            ],
            options={
                "verbose_name": "Configuración de la Tienda",
                "verbose_name_plural": "Configuración de la Tienda",
            },
        ),
    ]
