# Generated by Django 5.1.4 on 2026-02-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0019_configuraciontienda"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="fecha",
            new_name="fecha_hora",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="tienda",
        ),
        migrations.AddField(
            model_name="ticket",
            name="cajero_nombre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cambio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cliente_telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="ticket",
            name="descuento_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EMITIDO", "Emitido"),
                    ("CANCELADO", "Cancelado"),
                    ("REIMPRESO", "Reimpreso"),
                ],
                default="EMITIDO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="impuestos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_relacionados",
                to="boutique.pedido",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="snapshot_json",
            field=models.JSONField(
                blank=True,
                help_text="Copia íntegra de ítems, precios y datos al emitir",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sucursal_nombre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ticket",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="total_pagado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_asociados",
                to="boutique.venta",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="folio",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="novia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_relacionados",
                to="boutique.novia",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("VENTA", "Venta"),
                    ("APARTADO", "Apartado"),
                    ("PEDIDO", "Pedido/Hechura"),
                    ("AJUSTE", "Ajuste"),
                    ("DEVOLUCION", "Devolución"),
                ],
                default="VENTA",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Apartado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente_nombre", models.CharField(max_length=200)),
                ("cliente_telefono", models.CharField(max_length=20)),
                ("notas", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("VIGENTE", "Vigente"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                            ("ENTREGADO", "Entregado"),
                        ],
                        default="VIGENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "anticipo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "novia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apartados_independientes",
                        to="boutique.novia",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apartados",
                        to="boutique.pedido",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="apartado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_asociados",
                to="boutique.apartado",
            ),
        ),
        migrations.CreateModel(
            name="ApartadoItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("talla", models.CharField(blank=True, max_length=50)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "apartado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="boutique.apartado",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boutique.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("sku_snapshot", models.CharField(blank=True, max_length=100)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("talla", models.CharField(blank=True, max_length=50)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="boutique.ticket",
                    ),
                ),
            ],
        ),
    ]
