# Generated by Django 5.1.4 on 2026-02-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0021_pagopedido_referencia_producto_talla_especial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartado",
            name="folio",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
