# Generated by Django 5.1.4 on 2026-02-15 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0023_cortecaja_transferencia_esperada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartado",
            name="categoria_cache",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apartado",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.cliente",
            ),
        ),
        migrations.AddField(
            model_name="apartado",
            name="color_cache",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="apartado",
            name="evento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boda", "Boda"),
                    ("Graduación", "Graduación"),
                    ("XV años", "XV años"),
                    ("Fiesta", "Fiesta"),
                    ("Civil", "Civil"),
                    ("Formal", "Formal"),
                    ("Otro", "Otro"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="apartado",
            name="talla_cache",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="cliente",
            name="fecha_alta",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cliente",
            name="notas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.cliente",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="evento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boda", "Boda"),
                    ("Graduación", "Graduación"),
                    ("XV años", "XV años"),
                    ("Fiesta", "Fiesta"),
                    ("Civil", "Civil"),
                    ("Formal", "Formal"),
                    ("Otro", "Otro"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="categoria_cache",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="venta",
            name="color_cache",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="venta",
            name="evento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boda", "Boda"),
                    ("Graduación", "Graduación"),
                    ("XV años", "XV años"),
                    ("Fiesta", "Fiesta"),
                    ("Civil", "Civil"),
                    ("Formal", "Formal"),
                    ("Otro", "Otro"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="talla_cache",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
