# Generated by Django 5.1.4 on 2026-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0024_apartado_categoria_cache_apartado_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartado",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("VENTA_NORMAL", "Venta normal"),
                    ("DAMA_HONOR", "Dama de honor"),
                    ("HECHURA_ESPECIAL", "Hechura especial"),
                ],
                default="VENTA_NORMAL",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_evento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("VENTA_NORMAL", "Venta normal"),
                    ("DAMA_HONOR", "Dama de honor"),
                    ("HECHURA_ESPECIAL", "Hechura especial"),
                ],
                default="VENTA_NORMAL",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_pedido",
            field=models.CharField(
                choices=[
                    ("SOBRE_PEDIDO", "Sobre Pedido"),
                    ("HECHURA", "Hechura Especial"),
                ],
                default="SOBRE_PEDIDO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("VENTA_NORMAL", "Venta normal"),
                    ("DAMA_HONOR", "Dama de honor"),
                    ("HECHURA_ESPECIAL", "Hechura especial"),
                ],
                default="VENTA_NORMAL",
                max_length=30,
            ),
        ),
    ]
