# Generated by Django 5.1.4 on 2026-02-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0025_apartado_tipo_operacion_pedido_fecha_evento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="novia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="boutique.novia",
            ),
        ),
    ]
