# Generated by Django 5.1.4 on 2026-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0026_alter_pedido_novia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("NUEVO", "Nuevo"),
                    ("PENDIENTE_TELA", "Falta comprar tela"),
                    ("TELA_COMPRADA", "Tela comprada"),
                    ("EN_CONFECCION", "En confección"),
                    ("SOLICITADO", "Solicitado"),
                    ("EN_TRANSITO", "En tránsito"),
                    ("POR_RECOGER", "Por recoger"),
                    ("RECIBIDO", "Recibido en tienda"),
                    ("LISTO", "Listo en tienda"),
                    ("ENTREGADO", "Entregado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="NUEVO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="tipo_pedido",
            field=models.CharField(
                choices=[
                    ("HECHURA", "Hechura Especial (Taller)"),
                    ("IMPORTACION", "Importación"),
                    ("PROVEEDOR", "Pedido a Proveedor"),
                    ("ESPECIAL", "Pedido Especial"),
                    ("ESTANDAR_GRUPO", "Estándar Grupo / Dama"),
                    ("SOBRE_PEDIDO", "Sobre Pedido (Legacy)"),
                ],
                default="SOBRE_PEDIDO",
                max_length=20,
            ),
        ),
    ]
