# Generated by Django 5.1.4 on 2026-02-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0027_alter_pedido_estado_alter_pedido_tipo_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="dama",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfiles_dama",
                to="boutique.cliente",
            ),
        ),
    ]
