# Generated by Django 5.1.4 on 2026-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0028_dama_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartado",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("VENTA_NORMAL", "Venta normal"),
                    ("DAMA_HONOR", "Dama de honor"),
                    ("HECHURA", "Hechura"),
                    ("PEDIDO_EXTERNO", "Pedido Externo"),
                ],
                default="VENTA_NORMAL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("NUEVO", "Nuevo"),
                    ("PENDIENTE_TELA", "Falta comprar tela"),
                    ("TELA_COMPRADA", "Tela comprada"),
                    ("EN_CONFECCION", "En confección"),
                    ("SOLICITADO", "Solicitado"),
                    ("EN_PROCESO", "En proceso"),
                    ("POR_RECOGER", "Por recoger"),
                    ("RECIBIDO", "Recibido en tienda"),
                    ("LISTO", "Listo en tienda"),
                    ("ENTREGADO", "Entregado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="NUEVO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("VENTA_NORMAL", "Venta normal"),
                    ("DAMA_HONOR", "Dama de honor"),
                    ("HECHURA", "Hechura"),
                    ("PEDIDO_EXTERNO", "Pedido Externo"),
                ],
                default="VENTA_NORMAL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="tipo_pedido",
            field=models.CharField(
                choices=[
                    ("HECHURA", "Hechura Especial (Taller)"),
                    ("PEDIDO_EXTERNO", "Pedido Externo (Importación/Proveedor)"),
                    ("ESTANDAR_GRUPO", "Estándar Grupo / Dama"),
                    ("SOBRE_PEDIDO", "Sobre Pedido (Legacy)"),
                ],
                default="SOBRE_PEDIDO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("VENTA_NORMAL", "Venta normal"),
                    ("DAMA_HONOR", "Dama de honor"),
                    ("HECHURA", "Hechura"),
                    ("PEDIDO_EXTERNO", "Pedido Externo"),
                ],
                default="VENTA_NORMAL",
                max_length=30,
            ),
        ),
    ]
