# Generated by Django 5.1.4 on 2026-02-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0029_alter_apartado_tipo_operacion_alter_pedido_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="caja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="boutique.cortecaja",
            ),
        ),
    ]
