# Generated by Django 5.1.4 on 2026-02-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0030_ticket_caja"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartado",
            name="agenda_evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apartados_vinculados",
                to="boutique.citaagenda",
            ),
        ),
        migrations.AddField(
            model_name="apartado",
            name="fecha_entrega_estimada",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartado",
            name="notas_entrega",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="citaagenda",
            name="apartado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citas",
                to="boutique.apartado",
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="agenda_evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="novias_vinculadas",
                to="boutique.citaagenda",
            ),
        ),
        migrations.AddField(
            model_name="novia",
            name="notas_entrega",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="agenda_evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_vinculados",
                to="boutique.citaagenda",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="notas_entrega",
            field=models.TextField(blank=True),
        ),
    ]
