# Generated by Django 5.1.4 on 2026-02-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0031_apartado_agenda_evento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("response_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PROCESSING", max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="producto",
            unique_together=set(),
        ),
    ]
