# Generated by Django 5.2.15 on 2026-06-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0036_servicio_venta_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuraciontienda",
            name="horarios",
            field=models.TextField(
                blank=True,
                help_text="Ej: Lun-Vie 10:00-20:00",
                verbose_name="Horarios de atención",
            ),
        ),
        migrations.AlterField(
            model_name="medidas",
            name="largo_aproximado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Largo aprox.",
            ),
        ),
        migrations.AlterField(
            model_name="movimientocaja",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boutique.servicio",
            ),
        ),
        migrations.AlterField(
            model_name="pagoservicio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="secuencia",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        # unique_producto_variant constraint omitida intencionalmente:
        # la BD de producción tiene productos duplicados que la harían fallar.
    ]
