# Generated by Django 5.2.15 on 2026-06-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0038_fix_categorias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("BASTILLA", "Bastilla"),
                    ("TALLE", "Ajuste de talle"),
                    ("TIRANTE", "Tirante"),
                    ("CREMALLERA", "Cremallera"),
                    ("PECHO", "Ajuste de pecho"),
                    ("CADERA", "Ajuste de cadera"),
                    ("MANGA", "Manga"),
                    ("APLIQUE", "Aplique / Adorno"),
                    ("BORDADO", "Bordado"),
                    ("AJUSTE", "Ajuste general"),
                    ("OTRO", "Otro servicio"),
                ],
                default="AJUSTE",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                fields=(
                    "categoria",
                    "modelo",
                    "tela",
                    "color",
                    "talla",
                    "rasgo1",
                    "rasgo2",
                ),
                name="unique_producto_variant",
                nulls_distinct=False,
            ),
        ),
    ]
