# Generated by Django 5.2.16 on 2026-07-24 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0039_alter_servicio_tipo_producto_unique_producto_variant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedidasDama",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigente", models.BooleanField(db_index=True, default=True)),
                (
                    "busto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "cintura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "cadera",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "largo_aproximado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hombro",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "brazo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "espalda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "talle_delantero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "talle_trasero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "altura_busto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "separacion_busto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bajo_busto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "largo_talle",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hombro_pezon",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hombro_bajo_busto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("fecha_medicion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "dama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medidas_registradas",
                        to="boutique.dama",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medidas_dama_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medidas_dama_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_medicion", "-fecha_modificacion"],
            },
        ),
        migrations.CreateModel(
            name="VestidoDama",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=30, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CATALOGO", "De catálogo"),
                            ("ESPECIAL", "Modelo especial"),
                            ("HECHURA", "Hecho a la medida"),
                        ],
                        default="ESPECIAL",
                        max_length=20,
                    ),
                ),
                ("numero_modelo", models.CharField(blank=True, max_length=100)),
                ("descripcion_especial", models.TextField(blank=True)),
                ("talla", models.CharField(blank=True, max_length=10)),
                (
                    "foto_referencia",
                    models.ImageField(blank=True, null=True, upload_to="vestidos/"),
                ),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE_FABRICACION", "Pendiente de fabricación"),
                            ("PEDIDO", "Pedido / Solicitado"),
                            ("EN_TRANSITO", "En tránsito"),
                            ("LLEGO_A_TIENDA", "Llegó a tienda"),
                            ("RESERVADO", "Reservado para la dama"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                            ("DEVUELTO", "Devuelto"),
                        ],
                        db_index=True,
                        default="PEDIDO",
                        max_length=30,
                    ),
                ),
                ("llego_en", models.DateTimeField(blank=True, null=True)),
                ("entregado_en", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.color",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vestidos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vestidos",
                        to="boutique.dama",
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vestidos_entregados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "llego_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vestidos_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.modelo",
                    ),
                ),
                (
                    "pedido",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vestido_dama",
                        to="boutique.pedido",
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vestido_dama",
                        to="boutique.producto",
                    ),
                ),
                (
                    "tela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.tela",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoVestido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada — llegó a tienda"),
                            ("RESERVA", "Reserva — asignado a dama"),
                            ("SALIDA", "Salida — vendido o entregado"),
                            ("LIBERACION_RESERVA", "Liberación de reserva"),
                            ("DEVOLUCION", "Devolución"),
                            ("MERMA", "Merma o baja por daño"),
                        ],
                        max_length=25,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vestido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_vestido",
                        to="boutique.vestidodama",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
