# Generated by Django 5.2.16 on 2026-07-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0040_medidas_dama_vestido_trazabilidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=30, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VESTIDO", "Vestido (catálogo/importación)"),
                            ("HECHURA", "Hechura especial"),
                            ("ESPECIAL", "Modelo especial"),
                            ("ACCESORIO", "Accesorio"),
                            ("AJUSTE", "Ajuste / costura"),
                        ],
                        default="VESTIDO",
                        max_length=20,
                    ),
                ),
                ("numero_modelo", models.CharField(blank=True, max_length=50)),
                ("descripcion_especial", models.TextField(blank=True)),
                ("talla", models.CharField(blank=True, max_length=10)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="pedido_items/"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("SOLICITADO", "Solicitado"),
                            ("EN_PROCESO", "En proceso"),
                            ("POR_RECOGER", "Por recoger"),
                            ("LLEGO", "Llegó a tienda"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("llego_en", models.DateTimeField(blank=True, null=True)),
                ("entregado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.color",
                    ),
                ),
                (
                    "dama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedido_items",
                        to="boutique.dama",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.modelo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="boutique.pedido",
                    ),
                ),
                (
                    "tela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boutique.tela",
                    ),
                ),
                (
                    "vestido_dama",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedido_item",
                        to="boutique.vestidodama",
                    ),
                ),
            ],
            options={
                "ordering": ["creado_en"],
            },
        ),
    ]
