# Generated by Django 5.2.16 on 2026-07-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0041_pedido_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartado",
            name="estado",
            field=models.CharField(
                choices=[
                    ("VIGENTE", "Vigente"),
                    ("VENCIDO", "Vencido"),
                    ("LLEGO_A_TIENDA", "Llegó a tienda"),
                    ("CANCELADO", "Cancelado"),
                    ("ENTREGADO", "Entregado"),
                ],
                db_index=True,
                default="VIGENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="apartado",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="novia",
            name="activo",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="novia",
            name="fecha_boda",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cliente_nombre",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
