# Generated by Django 5.2.16 on 2026-07-24 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0042_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjusteLinea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BASTILLA", "Bastilla"),
                            ("TIRANTE", "Tirante"),
                            ("HOMBRO", "Hombro"),
                            ("PIERNA", "Pierna"),
                            ("CINTURA", "Cintura"),
                            ("BUSTO", "Busto"),
                            ("CIERRE", "Cierre / Cremallera"),
                            ("MANGA", "Manga"),
                            ("COSTADO", "Costado"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Detalle adicional. Requerido cuando tipo=OTRO.",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "prenda",
                    models.CharField(
                        blank=True,
                        help_text="Prenda o ítem relacionado",
                        max_length=200,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="boutique.servicio",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "pk"],
            },
        ),
    ]
