# Generated by Django 5.2.16 on 2026-07-24 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0043_ajuste_linea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talla",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20, unique=True)),
                (
                    "aliases_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de alias aceptados. Ej: ["ch", "chico", "small"]',
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Talla",
                "verbose_name_plural": "Tallas",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="modelo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modelos",
                to="boutique.categoria",
            ),
        ),
        migrations.AddField(
            model_name="modelo",
            name="codigo_especial",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="modelo",
            name="combinacion_telas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modelo",
            name="es_especial",
            field=models.BooleanField(
                default=False,
                help_text="Habilita campos adicionales para modelos hechos a medida",
            ),
        ),
        migrations.AddField(
            model_name="modelo",
            name="foto_principal",
            field=models.ImageField(blank=True, null=True, upload_to="modelos/"),
        ),
        migrations.AddField(
            model_name="modelo",
            name="notas_confeccion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modelo",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Número/código de referencia del modelo",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dama",
            name="talla_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="damas",
                to="boutique.talla",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="talla_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to="boutique.talla",
            ),
        ),
        migrations.AddField(
            model_name="pedidoitem",
            name="talla_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedido_items",
                to="boutique.talla",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="talla_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="boutique.talla",
                verbose_name="Talla (catálogo)",
            ),
        ),
        migrations.AddField(
            model_name="vestidodama",
            name="talla_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vestidos_dama",
                to="boutique.talla",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("modelo__isnull", False), ("talla_obj__isnull", False)
                ),
                fields=("modelo", "color", "tela", "talla_obj"),
                name="uq_variante_modelo_color_tela_talla",
            ),
        ),
    ]
