# Generated by Django 5.2.16 on 2026-07-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0045_talla_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuraciontienda",
            name="color_primario",
            field=models.CharField(
                default="#9D174D",
                help_text="Ej: #9D174D — controla botones, acentos y encabezado del ticket",
                max_length=7,
                verbose_name="Color primario (hex)",
            ),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="color_secundario",
            field=models.CharField(
                default="#F9A8D4",
                help_text="Ej: #F9A8D4 — gradientes y fondos suaves",
                max_length=7,
                verbose_name="Color secundario (hex)",
            ),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="tagline",
            field=models.CharField(
                blank=True,
                default="Alta moda nupcial · Cuernavaca",
                help_text="Ej: Alta moda nupcial · Cuernavaca",
                max_length=200,
                verbose_name="Tagline",
            ),
        ),
    ]
