# Generated by Django 5.2.16 on 2026-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0046_brand_identity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuraciontienda",
            name="site_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ej: https://pos.adeleboutique.com — se usa en el QR del ticket para llevar a la página de detalle del pedido",
                max_length=200,
                verbose_name="URL del sitio",
            ),
        ),
        migrations.AlterField(
            model_name="configuraciontienda",
            name="tagline",
            field=models.CharField(
                blank=True,
                default="Alta moda | Guadalajara | Santa Tere",
                help_text="Ej: Alta moda nupcial · Cuernavaca",
                max_length=200,
                verbose_name="Tagline",
            ),
        ),
    ]
