# Generated by Django 5.2.16 on 2026-07-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0047_add_site_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="activo",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Desactivar oculta el producto del inventario sin borrar el historial",
            ),
        ),
    ]
