# Generated by Django 5.2.16 on 2026-08-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0048_add_activo_to_producto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TicketItem",
        ),
    ]
