# Generated by Django 5.2.16 on 2026-08-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0049_remove_ticketitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoitem",
            name="largo",
            field=models.CharField(blank=True, max_length=20, verbose_name="Largo"),
        ),
    ]
