# Generated by Django 5.1.4 on 2026-10-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0050_add_largo_to_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='costo_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='precio_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
